import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Button } from "rsuite";
import API from "../src/api";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [AvialableData, setAvialableData] = useState({
    attrib: false,
    ptype: false,
  });
  useEffect(() => {
    const init=async () => {
      try {
        const res1 = await API.get("/attributes",{params:{count:true}});
        const res2 = await API.get("/product_types",{params:{count:true}});
        // console.log(res1.data);
        // console.log(res2.data);
        setAvialableData({
          attrib: res1.data,
          ptype: res2.data,
        });
      } catch (err) {
        console.log(err);
      }
    }
    init();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Fullstack challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the admin platform</h1>

        {/* <p className="text-red-700 py-8">
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}

        <div className={styles.grid}>
          <Link href="/products/attribute">
            <a className={styles.card}>
              <h2>attributes &rarr;</h2>
            </a>
          </Link>
          <Link href="/products/product_type">
            <a className={styles.card}>
              <h2>product_types &rarr;</h2>
            </a>
          </Link>

          <Button title="qsd" className={styles.card}>
            <Link href="/products/product">
              <h2>bbb &rarr;</h2>
            </Link>
          </Button>

          <Link href="/products/product">
            <a className={styles.card}>
              <h2>products &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/walid-hanniche/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-purple-900 py-2"
        >
          Powered by W{" "}
          {/*<span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  </span>*/}
        </a>
      </footer>
    </div>
  );
};

export default Home;
